from enum import Enum, EnumMeta
from typing import Any

class CompositeEnumMeta(EnumMeta):
    _composite_source_map_: dict[str, type[Enum]]
    _composite_includes_: tuple[type[Enum], ...]

    def included_enums(cls) -> tuple[type[Enum], ...]: ...
    def includes_enum(cls, source: type[Enum]) -> bool: ...
    def members_from(cls, source: type[Enum]) -> frozenset[Enum]: ...
    def to_source(cls, member: Enum) -> Enum | None: ...
    def from_source(cls, member: Enum) -> Enum | None: ...

class CompositeEnum(Enum, metaclass=CompositeEnumMeta):
    @property
    def source_enum(self) -> type[Enum] | None: ...
