from collections.abc import Sequence
from enum import Enum, EnumMeta
from typing import Any

class CompositeEnumMeta(EnumMeta):
    _composite_source_map_: dict[str, type[Enum]]
    _composite_includes_: tuple[type[Enum], ...]

    def included_enums(cls) -> tuple[type[Enum], ...]: ...
    def includes_enum(cls, source: type[Enum]) -> bool: ...
    def members_from(cls, source: type[Enum]) -> frozenset[Enum]: ...
    def from_source(cls, member: Enum) -> Enum | None: ...

class CompositeEnum(Enum, metaclass=CompositeEnumMeta):
    def __init_subclass__(
        cls,
        *,
        includes: type[Enum] | Sequence[type[Enum]] = (),
        **kwargs: Any,
    ) -> None: ...
    @property
    def source_enum(self) -> type[Enum] | None: ...
    def to_source(self) -> Enum | None: ...
